#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
sudo apt-get -y update
sudo apt-get install -y haproxy

echo "
defaults
    timeout connect 10s
    timeout client 30s
    timeout server 30s
    log global
    mode http

frontend haproxynode
    bind *:80
    mode http
    default_backend backendnodes

backend backendnodes
    balance roundrobin
    option forwardfor
    server 1543-web-01 104.196.116.233:80 check
    server 1543-web-02 54.165.130.77:80 check

listen stats
    bind :32700
    stats enable
    stats uri /" >> /etc/haproxy/haproxy.cfg

sudo haproxy -f /etc/haproxy/haproxy.cfg -c
sudo service haproxy restart
