#!/usr/bin/env bash
# This script is displaying  numbers from 1 to 100.
i=1
while (( i <= 100 ))
do
  
  if (( i % 5 == 0 )) && (( i % 3 == 0 )); then
    echo "FizzBuzz"

  elif (( i % 5 == 0 )); then
    echo "Buzz"
  
  elif (( i % 3 == 0 )); then
    echo "Fizz"
  
  else
    echo $i
  fi
  ((i++))
done
