#!/usr/bin/env bash
# This script is displaying "Holberton School" 9 times and one time "hi" using while
i=1
while (( i < 10 ))
do
  echo "Holberton School"
  ((i++))
  if [[ "$i" == '9' ]]; then
    echo "Hi"
  fi
done
