#!/usr/bin/env bash
# This script is displaying "Holberton School" 9 times and one time "hi" using while
i=1
while [[ $i -lt 10 ]]
do
  if [[ $i -eq 9 ]]; then
    echo "Hi"
  fi
  echo "Holberton School"
  ((i++))
done
