#!/usr/bin/env bash
# This script is displaying 1-20 with differents strings  using case statement
i=0
while (( i <= 19 ))
do
  ((i++)) 
  case $i in
   "4") echo -e "$i\nbad luck from China";;
   "9") echo -e "$i\nbad luck from Japan";;
   "17") echo -e "$i\nbad luck from Italy";;
   *) echo $i;;
  esac
done
